version: "2"

services:
  zk:
    image: "zookeeper:3.4"
    ports:
    - "2181:2181"

  kafka:
    image: "wurstmeister/kafka:0.10.2.0"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
    ports:
    - "9092:9092"
    depends_on:
    - "zk"

  mysql:
    image: "mariadb:10.1"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - "./var/mysql:/var/lib/mysql"

  tests:
    image: "openjdk:8-jdk"
    command: "./gradlew clean build --parallel"
    working_dir: "/telemetry"
    environment:
      GRADLE_USER_HOME: "/gradle"
      KAFKA_SERVERS: "kafka:9092"
    volumes:
    - "./build/docker/.gradle:/gradle"
    - "./:/telemetry"
    depends_on:
    - "kafka"
