/*
 * This file is generated by jOOQ.
*/
package me.dmexe.telemetry.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.dmexe.telemetry.jooq.tables.Pages;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Root extends SchemaImpl {

    private static final long serialVersionUID = -269307859;

    /**
     * The reference instance of <code>root</code>
     */
    public static final Root ROOT = new Root();

    /**
     * The table <code>root.pages</code>.
     */
    public final Pages PAGES = me.dmexe.telemetry.jooq.tables.Pages.PAGES;

    /**
     * No further instances allowed
     */
    private Root() {
        super("root", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Pages.PAGES);
    }
}
