/*
 * This file is generated by jOOQ.
*/
package me.dmexe.telemetry.jooq;


import javax.annotation.Generated;

import me.dmexe.telemetry.jooq.tables.Pages;


/**
 * Convenience access to all tables in root
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>root.pages</code>.
     */
    public static final Pages PAGES = me.dmexe.telemetry.jooq.tables.Pages.PAGES;
}
