# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "gradle/versions.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

      - run: gradle downloadDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v3-dependencies-{{ checksum "gradle/versions.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_test_results:
          path: netty/build/test-results/junit-platform

      - store_artifacts:
          path: netty/build/reports
          destination: netty-reports

